language: java
env:
  global:
  - CC_TEST_REPORTER_ID=45ea9dad0d4eb801ab7e281b2edceebc1204d5a4741dbb61b428af8639ddf2a3
  - secure: iQFU+s7iksRXMzKEinEfrNWhKZDgjPh40nPZhR586p4kAoJZg8O5byBTZDbIJGlJUXKHnxaDjQUaFVhaSL//9tI5LcA0xxmX9+KFI9uwKQSE3GGT0f8TX7qlhixJDUXl2AIKEIZFx5cdb6Csh4HYEpmE8kmOFCbjYkrP2qOGKSZu6dky0lnBcA9o//GVtFN/yK6Yo04OWio9VmNpBqFXuXxSW+Pq4cKwmU8VYVtnnxRhGo4w1CaMXYjsCJ3dYsu2d1AZJ/GF3KmC9QljAQgHl2bk4l8MOYiHASnemJr8E01unf2/6awbV+6DtY55pBgobjNQmAMK7CeXmjhIzsYBRZ0ezNSHOUIz9wXupTBE9pyqX9t4BhiBjVO/NYXfknaNkJx2/C1E2pzTO7SuX2FpdvrO2PriFMK4kC42L6W7gLxrCv+QYCNL634Ozial0l+M9n1wh/ArK+HBNZwQuFENXq/TSMWx5LC7l1fEd4HjrHiwmuHGSuoNXHnhcPDcsgHq4aQ14ALoTMOdPvNrvWTQmROjQlFNFca8V+C/ma9iVt8ajteCxqpAcllIXMBKoD2mdMGxavftOLi4Pk1tXd0lWSDmXbOtdUO3n96S2DwxtXRGOaK0J3zocrim+VJkLMB3XSXB7fduzr/3Ettnig/vNhDSXy2H1oeOWqo+tpHpwOs=
  - secure: bADd2MEckM02ShLcWxyK8N2lEjQ7Pk1zc3RNzEnY37iuqGrYquf8AFyvy0b91EETx1ZNILNebpfbyR+a+nEJimM7f4kmoFfTC365A5J1f19AidvHiP1IEs34NzO6NofpBOA1BmTT6Qcx4HQ2ltG2N1nVLKkL0MJPunMA8hZsqEt0epTeiiCO+90+w7cFmFF7bJ74/+T2KQKwHPMmiVvt7JlYZ1clw4b/ouoh4hksKxxYHOHdrPrzqiTkkP8Kw4zm1Nc5bgbH3mKiPADducplF2CWc2dwyJDDlSY67irknkkcMh+JoysPW+Ibcjem+mqv1OWidiw2aYUotwQnLPXd0Is45sDKWPGkHb+44jzcT9f0y/PS01jy2kKfWmPtDy+gv/ZMu+vpwgVkrcg//XlbkH6D+B2xS8aJEOFzm7MqpVSzoSpZiZZ5nQWxkGiBFJbk3F4IKrtnOg3telKSkkjl4eBIvGGMa7id2Kmpn6JO9W6UZ8vzv9gvvHE9FQ91yJR5rwWK1L6Qj4L6m3Wjot9KQi5C5j2ZSdfprlqc9FrXvbYr4ZRsynJHNC3FQxgKaM9JCf+uHN0kNM3pEo251yUnIS67ciHf58dSSEUXdoOzmwGU50smA+gWv+oSJh/11cGrR8RjHBglWCwMKPu1MRr8hyXkelfNO1QyIHU5wYQxQwg=
  - secure: LNnKEK8vMbujpxCZ2IE3EtwJ5AUqhfaBf3vNNQW9yUPJaW9j+ZSF3s0pHjNH8ZQnhPo9Asy26I4VCIyJPVCBPTNedzAZfNfJNCnJWvScoBJdcxdPn2ou4ni5XU7FlSU2aPT3dB9gW7RJPZMnVR7SzJfdpARe9uoetkzi7D+zzBavhDHLiwZon0GaA2eDASekNSbVF5hfidhXFiTVC0YMj5Bj5abNkkvDXanwQJKwzpq9JRMcoFFQ8mBUTpZPbnu9xe0mvqiejm2inBpCXWcSVgk0r2NkwehmPNLkH6gnyrZ0HKPV4XJ7LSjoN6GW7OVNpvyTpgbg9HJq2CO+opRUZjrJ/zNFZ7tRL02oUOnN03zhitWvAsMn9dypngu+UMldLX9YhkS2lLAHhNJ5RrQAcn4mi65KNXkD7eLwNzXjELmBH6Sb5vWR2EFLqOw27GOskPD5EqU/hEaZoRahpcXPGOOuBGKQOHLFxJ4EqYEtj8fscsfylazZ88dxZN0575cq9zheKeFZzqfNufhOKkoXU3TMETjD39xC1YAxM2d8g0Y/Ki88GWQ8D6Gi3wxwmc5JRLWrEXqXf5vNpUdeQofPV/7v/UUW8KSPNQ1QxdhE+4dt16RhAQYz380q1+JiHsb7MGtkdWG+3WHkF+De0yGObJgm+MtXigmhPSXzZBHAI5U=
install:
- mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true
  -B -V
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
- ".travis/before-script.sh"
script:
- mvn test
after_script:
- "./cc-test-reporter format-coverage -d -t jacoco ./target/jacoco-ut/jacoco.xml"
- "./cc-test-reporter upload-coverage -d"
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
deploy:
- provider: script
  script: ".travis/deploy.sh"
  skip_cleanup: true
  on:
    repo: trickl/assertj-json-serialize
    all_branches: true
- provider: releases
  api_key:
    secure: kM24jsvnQzf3PUVYyECP+YY53yi9juOpGr6NKQgKTdHjP8PAica0JS/20/0OrfBMdnb3BFWQFs65rQMojv8V67HsxXUoYwXbD2oKk4gFjil/Z3L5sXosBsn7dnbfhG1ctrtkpt/zweSLyPo9puF9NGK3r2gDu1XCJSs1e6qKQNyIEWEDJn+zaC7PEc2BPFUp+uzLOQFVDNPB2nTX+mSY8GDovfECS9Skm4iHUg0aplyfw8bO1H/SoE/4F/Vese2fetOG+xjqEClrxt9JfSe3sVHNgrNo6yT1QmDtXSS13cymonUefaxJcQ9pDa1pIBK6qdRKGK7a/0anE6cWVCShAFdIGAoFjoX+QMBmhaIKBvZ2cW/MlkuEFYkksaZYvcmJKktm3Jh7IyUhFJaKkWILTNc8FOQTyx3+3DoXxby/1Lf9rwY/gbG79Rhb/ipLDTKmskfnoqWarR1X6buemUfYJ1WESFfaAqcdwk6B25ESB6vSa+kg1Tg8/3cn+AxW0jpygNpSXGwvTBASbsoIrbJPLtgoOMQeq/rT+GlRveApgRWvE9Jo183bGhur5azZyuBALpVEAVJuZIGUARz6JDb5J5nhcmoqV03OEz5ZYZgHqDiWaczyVnOpG3VXdLZ9+Bq4XNQBDRfhqapxB35rRsE0H/qLT5uf/6Bg2pYKD20/uIw=
  file: ".travis.yml"
  on:
    repo: trickl/assertj-json-serialize
